Repository parthenon-hpc-lab/parthenon, pull requests merged in 2020-10, with the labels that each got.

#313 Include guards in cmake for Kokkos
  CHANGELOG.md
  CMakeLists.txt
Labels: refactor

#291 Add Task diagram illustrating relationship between classes
  CHANGELOG.md
  docs/TaskDiagram.png
  docs/tasks.md
Labels: documentation

#320 Avoid initializing MPI in regression tests
  tst/regression/run_test.py
Labels: bug

#281 Joshua s brown/detect nvidia gpus
  .gitlab-ci-ias.yml
  CHANGELOG.md
  CMakeLists.txt
  CONTRIBUTING.md
  cmake/CTestCustom.cmake.in
  cmake/TestSetup.cmake
  cmake/machinecfg/CI.cmake
  docs/building.md
  scripts/device_check.sh
  tst/regression/CMakeLists.txt
  tst/regression/run_test.py
  tst/regression/test_suites/advection_convergence/advection_convergence.py
  tst/regression/test_suites/advection_performance/advection_performance.py
  tst/regression/test_suites/calculate_pi/calculate_pi.py
  tst/regression/test_suites/output_hdf5/output_hdf5.py
  tst/regression/test_suites/restart/restart.py
  tst/regression/utils/test_case.py
Labels: Kokkos, enhancement, performance, refactor, testing

#308 Add Cache for MeshBlockPacks
  CHANGELOG.md
  docs/interface/state.md
  docs/mesh/packing.md
  example/calculate_pi/calculate_pi.cpp
  example/calculate_pi/parthinput.example
  example/calculate_pi/pi_driver.cpp
  src/CMakeLists.txt
  src/interface/metadata.hpp
  src/interface/properties_interface.hpp
  src/interface/state_descriptor.hpp
  src/interface/variable_pack.hpp
  src/mesh/amr_loadbalance.cpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  src/mesh/meshblock.cpp
  src/mesh/meshblock.hpp
  src/mesh/meshblock_pack.hpp
  src/parthenon/package.hpp
  src/utils/partition_stl_containers.hpp
  tst/unit/test_partitioning.cpp
Labels: enhancement, performance

#325 Fix multi rank convergence tests
  CHANGELOG.md
  cmake/machinecfg/CI.cmake
  tst/regression/test_suites/advection_convergence/advection_convergence.py
  tst/regression/test_suites/advection_performance/advection_performance.py
  tst/regression/test_suites/calculate_pi/calculate_pi.py
  tst/regression/test_suites/output_hdf5/output_hdf5.py
  tst/regression/test_suites/restart/restart.py
Labels: bug, ci, testing

#311 Restart bugfix
  CHANGELOG.md
  src/interface/variable_pack.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh_refinement.cpp
  src/outputs/parthenon_hdf5.cpp
  src/outputs/restart.cpp
  src/outputs/restart.hpp
  src/parthenon_manager.cpp
  tst/regression/test_suites/restart/restart.py
Labels: bug

#336 Add memcpy check to CI
  .gitlab-ci.yml
  CHANGELOG.md
  scripts/docker/Dockerfile.nvcc
Labels: ci, testing

#330 Close h5py files after reading, and issue with np array access when using h5py
  CHANGELOG.md
  tst/regression/test_suites/restart/restart.py
Labels: bug, ci, testing

#340 Add parthenon root dir to parameters
  tst/regression/test_suites/output_hdf5/output_hdf5.py
  tst/regression/utils/test_case.py
Labels: refactor, testing
