Repository parthenon-hpc-lab/parthenon, pull requests merged in 2020-09, with the labels that each got.

#292 Fix broken nightly CI test
  .gitlab-ci-ias.yml
  .gitlab-ci.yml
  cmake/machinecfg/CI.cmake
Labels: bug, ci, testing

#290 Add per cycle performance output
  CHANGELOG.md
  docs/README.md
  docs/inputs.md
  src/driver/driver.cpp
  src/driver/driver.hpp
  src/mesh/mesh.hpp
  src/mesh/meshblock.cpp
  tst/regression/test_suites/advection_performance/parthinput.advection_performance
Labels: Kokkos, performance

#298 Infrastructure Required to Support MeshPacks of arbitrary size.
  CHANGELOG.md
  docs/mesh/packing.md
  example/calculate_pi/calculate_pi.cpp
  example/calculate_pi/calculate_pi.hpp
  example/calculate_pi/parthinput.example
  example/calculate_pi/pi_driver.cpp
  example/calculate_pi/pi_driver.hpp
  src/driver/driver.hpp
  src/mesh/meshblock_pack.hpp
  src/parthenon/driver.hpp
  src/parthenon/package.hpp
  src/parthenon/prelude.hpp
  src/utils/partition_stl_containers.hpp
  tst/unit/CMakeLists.txt
  tst/unit/test_partitioning.cpp
Labels: Kokkos, enhancement

#289 added weak scaling instructions
  docs/weak_scaling.md
  example/advection/parthinput.advection
Labels: documentation, performance

#303 make block_list a std::vector instead of a std::list
  CHANGELOG.md
  docs/mesh/mesh.md
  example/advection/parthenon_app_inputs.cpp
  example/calculate_pi/pi_driver.cpp
  example/face_fields/face_fields_example.cpp
  example/kokkos_pi/kokkos_pi.cpp
  src/driver/driver.cpp
  src/driver/driver.hpp
  src/mesh/amr_loadbalance.cpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  src/mesh/meshblock_pack.hpp
  src/outputs/parthenon_hdf5.cpp
  src/outputs/parthenon_hdf5.hpp
  src/outputs/restart.cpp
  src/outputs/vtk.cpp
  src/parthenon/driver.hpp
  src/parthenon_manager.cpp
  src/utils/partition_stl_containers.hpp
  tst/unit/test_partitioning.cpp
Labels: performance
