Repository parthenon-hpc-lab/parthenon, pull requests merged in 2020-11, with the labels that each got.

#200 Adjusting gitlab yml for internal trigger of ci
  .gitlab-ci-darwin.yml
  .gitlab-ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  scripts/darwin/build.sh
  scripts/darwin/build_hdf5_parallel.sh
  scripts/darwin/get_cpp.sh
  scripts/darwin/get_package.sh
  scripts/darwin/get_version.sh
  scripts/darwin/setup.sh
Labels: ci, enhancement, testing

#347 Joshua s brown/ci darwin speedup
  .gitlab-ci-darwin.yml
  CHANGELOG.md
  scripts/darwin/build_fast.sh
Labels: ci, refactor

#353 Fixing parameter_input
  CHANGELOG.md
  src/parameter_input.cpp
Labels: Error, invalid

#368 Joshua s brown/fix false positive ci
  CHANGELOG.md
  scripts/darwin/build_fast.sh
Labels: Error, ci

#332 Boundary conditions
  CHANGELOG.md
  CMakeLists.txt
  docs/boundary_conditions.md
  docs/mesh/domain.md
  example/advection/advection_driver.cpp
  src/application_input.hpp
  src/bvals/boundary_conditions.cpp
  src/bvals/boundary_conditions.hpp
  src/bvals/boundary_flag.cpp
  src/bvals/bvals.hpp
  src/bvals/bvals_interfaces.hpp
  src/bvals/bvals_refine.cpp
  src/defs.hpp
  src/interface/mesh_data.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/interface/variable.cpp
  src/interface/variable_pack.hpp
  src/mesh/domain.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  src/mesh/mesh_refinement.cpp
  src/mesh/meshblock.cpp
  src/mesh/meshblock.hpp
  tst/regression/CMakeLists.txt
  tst/regression/test_suites/advection_outflow/__init__.py
  tst/regression/test_suites/advection_outflow/advection_outflow.py
  tst/regression/test_suites/advection_outflow/parthinput.advection_outflow
  tst/unit/test_meshblock_data_iterator.cpp
  tst/unit/test_unit_domain.cpp
Labels: enhancement

#369 Fix submodules by calling update init
  .gitlab-ci-darwin.yml
  CHANGELOG.md
Labels: Error, ci
