Repository parthenon-hpc-lab/parthenon, pull requests merged in 2020-07, with the labels that each got.

#187 Joshua s brown/add code coverage
  .gitlab-ci.yml
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  cmake/CodeCov.cmake
  cmake/TestSetup.cmake
  codecov.yml
  docs/building.md
  scripts/combine_coverage.sh
  tst/regression/CMakeLists.txt
  tst/regression/run_test.py
  tst/regression/test_suites/advection_convergence/advection_convergence.py
  tst/regression/test_suites/calculate_pi/calculate_pi.py
  tst/regression/test_suites/output_hdf5/output_hdf5.py
  tst/regression/utils/test_case.py
  tst/unit/kokkos_abstraction.cpp
  tst/unit/test_container_iterator.cpp
  tst/unit/test_error_checking.cpp
  tst/unit/test_metadata.cpp
  tst/unit/test_pararrays.cpp
  tst/unit/test_required_desired.cpp
  tst/unit/test_taskid.cpp
  tst/unit/test_unit_domain.cpp
  tst/unit/test_unit_face_variables.cpp
  tst/unit/test_unit_params.cpp
Labels: ci, enhancement, testing

#210 Clean up error checking in params
  docs/README.md
  src/interface/params.hpp
  src/utils/error_checking.hpp
  tst/unit/test_unit_params.cpp
Labels: enhancement

#224 Add performance regression test
  .gitlab-ci-ias.yml
  .gitlab-ci.yml
  CONTRIBUTING.md
  scripts/docker/Dockerfile.nvcc
  tst/regression/CMakeLists.txt
  tst/regression/run_test.py
  tst/regression/test_suites/advection_performance/__init__.py
  tst/regression/test_suites/advection_performance/advection_performance.py
  tst/regression/test_suites/advection_performance/parthinput.advection_performance
  tst/regression/utils/test_case.py
Labels: ci, performance, testing

#234 Correct CMAKE variable, make local to project
  cmake/CodeCov.cmake
  cmake/TestSetup.cmake
  tst/regression/CMakeLists.txt
Labels: bug, testing

#235 Adjust coverage settings so coverage fail is not so sensitive
  codecov.yml
Labels: ci, testing

#236 Move gold standard to GitHub and add CMake target
  .gitlab-ci.yml
  CMakeLists.txt
  docs/README.md
  docs/building.md
  tst/regression/gold_standard/current_version
Labels: testing

#204 Add Physical Constants
  docs/constants.md
  src/utils/constants.hpp
  src/utils/utils.hpp
  tst/unit/CMakeLists.txt
  tst/unit/test_unit_constants.cpp
Labels: enhancement

#245 used absolute path for parthenon scripts instead of relative paths
  cmake/TestSetup.cmake
  tst/regression/test_suites/output_hdf5/output_hdf5.py
Labels: refactor
