Repository parthenon-hpc-lab/parthenon, pull requests merged in 2020-08, with the labels that each got.

#226 Updated workflow with separate develop branch
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation, question

#262 Fix code coverage test
  .gitlab-ci-ias.yml
  .gitlab-ci.yml
  CMakeLists.txt
  cmake/CodeCov.cmake
  cmake/Lint.cmake
  cmake/TestSetup.cmake
  tst/unit/CMakeLists.txt
  tst/unit/kokkos_abstraction.cpp
  tst/unit/test_container_iterator.cpp
  tst/unit/test_error_checking.cpp
  tst/unit/test_metadata.cpp
  tst/unit/test_pararrays.cpp
  tst/unit/test_required_desired.cpp
  tst/unit/test_taskid.cpp
  tst/unit/test_unit_constants.cpp
  tst/unit/test_unit_domain.cpp
  tst/unit/test_unit_face_variables.cpp
  tst/unit/test_unit_params.cpp
Labels: bug, testing

#243 Added cmake module which checks for required python modules, updated …
  README.md
  cmake/PythonModuleCheck.cmake
  cmake/TestSetup.cmake
  tst/regression/CMakeLists.txt
  tst/regression/test_suites/output_hdf5/output_hdf5.py
Labels: refactor

#238 Add ability to install Parthenon as a library/CMake package
  CMakeLists.txt
  cmake/parthenonConfig.cmake.in
  docs/building.md
  src/CMakeLists.txt
Labels: enhancement

#279 add metadata documentation for fillghosts
  docs/interface/Metadata.md
Labels: documentation

#280 added build option for num mpi testning
  docs/building.md
Labels: documentation

#263 Variable packs over the entire mesh
  CHANGELOG.md
  docs/mesh/packing.md
  example/calculate_pi/calculate_pi.cpp
  example/calculate_pi/calculate_pi.hpp
  example/calculate_pi/parthinput.example
  example/calculate_pi/pi_driver.cpp
  src/interface/variable_pack.hpp
  src/mesh/domain.hpp
  src/mesh/mesh.hpp
  src/mesh/mesh_pack.hpp
Labels: Kokkos, enhancement, help wanted, performance, question
