Repository parthenon-hpc-lab/parthenon, pull requests merged in 2021-06, with the labels that each got.

#531 Changed lambda to for-loop to work around gcc7.3.0
  CHANGELOG.md
  src/outputs/parthenon_hdf5.cpp
Labels: bug

#539 Fix restart bug
  CHANGELOG.md
  src/parthenon_manager.cpp
  src/parthenon_manager.hpp
Labels: bug

#520 Update apply-formatting.yml
  .github/workflows/apply-formatting.yml
  .github/workflows/check-formatting.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  cmake/Format.cmake
  scripts/python/packages/parthenon_performance_app/bin/parthenon_metrics_app.py
  scripts/python/packages/parthenon_performance_app/parthenon_performance_app/__init__.py
  scripts/python/packages/parthenon_performance_app/parthenon_performance_app/githubapp.py
  scripts/python/packages/parthenon_performance_app/parthenon_performance_app/parthenon_performance_advection_analyzer.py
  scripts/python/packages/parthenon_performance_app/parthenon_performance_app/parthenon_performance_json_parser.py
  scripts/python/packages/parthenon_performance_app/parthenon_performance_app/parthenon_performance_plotter.py
  scripts/python/packages/parthenon_performance_app/setup.py
  scripts/python/packages/parthenon_tools/parthenon_tools/__init__.py
  scripts/python/packages/parthenon_tools/parthenon_tools/movie2d.py
  scripts/python/packages/parthenon_tools/parthenon_tools/phdf.py
  scripts/python/packages/parthenon_tools/parthenon_tools/phdf_diff.py
  scripts/python/packages/parthenon_tools/setup.py
  tst/regression/run_test.py
  tst/regression/test_suites/advection_convergence/advection_convergence.py
  tst/regression/test_suites/advection_outflow/advection_outflow.py
  tst/regression/test_suites/advection_performance/advection_performance.py
  tst/regression/test_suites/calculate_pi/calculate_pi.py
  tst/regression/test_suites/output_hdf5/output_hdf5.py
  tst/regression/test_suites/restart/restart.py
  tst/regression/utils/test_case.py
  tst/style/cpplint.py
Labels: enhancement

#476 Prepare for C++17 and sync CMake min version
  .gitlab-ci-ias.yml
  CHANGELOG.md
  CMakeLists.txt
  docs/building.md
  src/CMakeLists.txt
  tst/unit/test_pararrays.cpp
Labels: build configuration, performance

#519 Add SHA256 checksum to bash uploader script
  CHANGELOG.md
  cmake/CodeCov.cmake
  cmake/CodeCovBashDownloadScript.cmake
Labels: security

#538 fix coarse buffer vs amr incompatibility. Resolves issue #537.
  CHANGELOG.md
  docs/interface/Metadata.md
  src/interface/metadata.hpp
  src/interface/variable.cpp
  src/mesh/meshblock.cpp
Labels: bug

#551 Hotfix to make particles compile without MPI again
  CHANGELOG.md
  example/particle_leapfrog/particle_leapfrog.cpp
  example/particle_tracers/particle_tracers.cpp
  example/particles/particles.cpp
  src/bvals/bvals_swarm.cpp
  src/interface/swarm.cpp
Labels: Fix, bug

#549 Add Deep code badge
  CHANGELOG.md
  README.md
Labels: ci

#554 Fix documentation in python-tools package
  CHANGELOG.md
  scripts/python/packages/parthenon_tools/README.md
Labels: documentation
