Repository parthenon-hpc-lab/parthenon, pull requests merged in 2021-01, with the labels that each got.

#403 Cleanup some Codacy warnings
  CHANGELOG.md
  src/driver/multistage.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/interface/swarm_container.cpp
  src/interface/swarm_container.hpp
  src/interface/variable.hpp
  src/outputs/outputs.hpp
  src/outputs/parthenon_hdf5.hpp
  src/outputs/restart.hpp
  src/parameter_input.cpp
  src/parameter_input.hpp
Labels: refactor

#402 Fix initital timestep calculation for `MeshData` functions
  CHANGELOG.md
  src/driver/driver.cpp
  src/interface/mesh_data.hpp
  src/mesh/mesh.hpp
Labels: bug

#422 Joshua s brown/version 0.4
  CHANGELOG.md
  CMakeLists.txt
Labels: version

#359 Buffer-pack-in-one
  CHANGELOG.md
  example/advection/advection_driver.cpp
  example/advection/advection_package.cpp
  example/advection/parthinput.advection
  src/CMakeLists.txt
  src/bvals/cc/bvals_cc.cpp
  src/bvals/cc/bvals_cc_in_one.cpp
  src/bvals/cc/bvals_cc_in_one.hpp
  src/interface/mesh_data.hpp
  src/interface/meshblock_data.cpp
  src/parthenon_manager.cpp
  src/reconstruct/dc_inline.hpp
  src/reconstruct/plm_inline.hpp
  tst/regression/test_suites/advection_convergence/parthinput.advection
  tst/regression/test_suites/advection_performance/parthinput.advection_performance
  tst/regression/test_suites/output_hdf5/parthinput.advection
Labels: performance

#425 Remove ambiguity in package names.
  CHANGELOG.md
  example/advection/advection_driver.cpp
  example/advection/advection_package.cpp
  example/advection/parthenon_app_inputs.cpp
  example/calculate_pi/calculate_pi.cpp
  example/calculate_pi/pi_driver.cpp
  example/face_fields/face_fields_example.cpp
  example/particles/particles.cpp
  src/interface/state_descriptor.cpp
  src/interface/state_descriptor.hpp
  src/interface/update.hpp
  src/parthenon_manager.cpp
  src/pgen/default_pgen.cpp
  src/refinement/refinement.cpp
  tst/unit/test_state_descriptor.cpp
Labels: api, bug

#410 Joshua s brown/fix python cpplint to call python3
  CHANGELOG.md
  cmake/Lint.cmake
  cmake/TestSetup.cmake
Labels: Error, build configuration, ci

#407 Joshua s brown/codacy cleanup2
  CHANGELOG.md
  example/calculate_pi/pi_driver.cpp
  scripts/darwin/build.sh
  scripts/darwin/build_hdf5_parallel.sh
  scripts/darwin/get_cpp.sh
  scripts/darwin/get_package.sh
  scripts/darwin/get_version.sh
  scripts/darwin/setup.sh
  scripts/python/phdf_diff.py
  src/coordinates/uniform_cartesian.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/interface/meshblock_data_iterator.hpp
  src/interface/metadata.cpp
  src/interface/variable.hpp
  src/interface/variable_pack.hpp
  src/mesh/amr_loadbalance.cpp
  src/outputs/outputs.hpp
  src/parameter_input.cpp
  src/tasks/task_types.hpp
  tst/performance/test_meshblock_data_iterator.cpp
  tst/regression/utils/test_case.py
  tst/unit/kokkos_abstraction.cpp
Labels: refactor

#428 Update copyright for all files that LANL employees touched in 2021
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CMakeLists.txt
  cmake/CheckCopyright.cmake
  cmake/CheckCopyrightScript.cmake
  src/driver/driver.cpp
  src/driver/multistage.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/interface/swarm_container.cpp
  src/interface/swarm_container.hpp
  src/interface/variable.hpp
  src/mesh/mesh.hpp
  src/outputs/outputs.hpp
  src/outputs/parthenon_hdf5.hpp
  src/outputs/restart.hpp
  src/parameter_input.cpp
  src/parameter_input.hpp
  src/parthenon/driver.hpp
Labels: build configuration
