Repository parthenon-hpc-lab/parthenon, pull requests merged in 2021-02, with the labels that each got.

#413 Add machine configuration for LANL Snow
  CHANGELOG.md
  cmake/PythonModuleCheck.cmake
  cmake/TestSetup.cmake
  cmake/machinecfg/Snow.cmake
  docs/building.md
  tst/regression/CMakeLists.txt
Labels: build configuration

#435 Separate num ranks from other mpi options
  CHANGELOG.md
  cmake/PythonModuleCheck.cmake
  cmake/TestSetup.cmake
  tst/regression/run_test.py
  tst/regression/utils/test_case.py
Labels: bug

#436 Update Summit build doc and machine file
  CHANGELOG.md
  cmake/machinecfg/Summit.cmake
  docs/building.md
Labels: build configuration, documentation

#438 More diagnostic runtime output (AMR/Loadbalance and mesh structure)
  CHANGELOG.md
  docs/inputs.md
  src/basic_types.hpp
  src/driver/driver.cpp
  src/driver/driver.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
Labels: performance

#377 Add machine config file for RZAnsel
  CHANGELOG.md
  cmake/TestSetup.cmake
  cmake/machinecfg/RZAnsel.cmake
  docs/building.md
  src/CMakeLists.txt
Labels: build configuration

#443 Fix Darwin config use spectrum with ppc64le
  CHANGELOG.md
  cmake/TestSetup.cmake
  cmake/machinecfg/Darwin.cmake
Labels: Error, build configuration, ci, testing

#441 Fix type used to parse `pack_size`
  CHANGELOG.md
  src/mesh/mesh.cpp
Labels: bug

#444 Output performance metrics for ci
  CHANGELOG.md
  tst/regression/test_suites/advection_performance/advection_performance.py
Labels: ci, performance, testing

#440 Add abstraction for allocating a unique_ptr to device memory
  CHANGELOG.md
  docs/development.md
  src/kokkos_abstraction.hpp
  tst/unit/kokkos_abstraction.cpp
Labels: enhancement

#451 Remove ran2 interface (and source)
  CHANGELOG.md
  src/utils/ran2.cpp
  src/utils/utils.hpp
Labels: bug, question

#453 Fix bounds and use vector
  CHANGELOG.md
  src/mesh/mesh.cpp
Labels: bug
