Repository parthenon-hpc-lab/parthenon, pull requests merged in 2021-07, with the labels that each got.

#557 plug in InitUserMeshBlockData
  CHANGELOG.md
  docs/README.md
  docs/amr.md
  example/calculate_pi/calculate_pi.cpp
  example/calculate_pi/calculate_pi.hpp
  example/calculate_pi/pi_driver.cpp
  example/calculate_pi/pi_driver.hpp
  src/application_input.hpp
  src/interface/mesh_data.hpp
  src/mesh/mesh.cpp
  src/mesh/meshblock.cpp
  src/mesh/meshblock.hpp
  src/pgen/default_pgen.cpp
Labels: enhancement

#564 Add EstimateTimestep to particles example task list
  CHANGELOG.md
  example/particles/particles.cpp
Labels: bug

#535 Sparse interface update
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  docs/interface/Metadata.md
  docs/interface/state.md
  docs/mesh/mesh.md
  docs/outputs.md
  example/advection/advection_package.cpp
  example/calculate_pi/calculate_pi.cpp
  example/calculate_pi/parthinput.example
  example/kokkos_pi/kokkos_pi.cpp
  example/stochastic_subgrid/stochastic_subgrid_package.cpp
  scripts/python/packages/parthenon_tools/parthenon_tools/phdf_diff.py
  src/CMakeLists.txt
  src/bvals/boundary_conditions.cpp
  src/interface/mesh_data.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/interface/meshblock_data_iterator.hpp
  src/interface/metadata.cpp
  src/interface/metadata.hpp
  src/interface/sparse_pool.cpp
  src/interface/sparse_pool.hpp
  src/interface/sparse_variable.cpp
  src/interface/sparse_variable.hpp
  src/interface/state_descriptor.cpp
  src/interface/state_descriptor.hpp
  src/interface/update.cpp
  src/interface/update.hpp
  src/interface/variable.cpp
  src/interface/variable.hpp
  src/interface/variable_pack.hpp
  src/mesh/meshblock.cpp
  src/mesh/meshblock_pack.hpp
  src/outputs/parthenon_hdf5.cpp
  src/outputs/vtk.cpp
  src/parthenon/package.hpp
  src/parthenon_manager.cpp
  src/refinement/amr_criteria.cpp
  src/refinement/amr_criteria.hpp
  src/utils/string_utils.cpp
  src/utils/utils.hpp
  tst/performance/test_meshblock_data_iterator.cpp
  tst/regression/test_suites/calculate_pi/parthinput.regression
  tst/unit/test_data_collection.cpp
  tst/unit/test_meshblock_data_iterator.cpp
  tst/unit/test_metadata.cpp
  tst/unit/test_state_descriptor.cpp
Labels: enhancement

#560 Make variable more appropriately generic
  CHANGELOG.md
  scripts/python/packages/parthenon_performance_app/bin/parthenon_metrics_app.py
Labels: refactor

#555 Joshua s brown/ci documentation
  .gitlab-ci-darwin.yml
  CHANGELOG.md
  scripts/darwin/base_setup.sh
  scripts/darwin/build_fast.sh
  scripts/darwin/install_python_scripts.sh
  scripts/darwin/metrics.sh
  scripts/darwin/setup.sh
Labels: documentation

#572 fix meshblock pack issues coming from template shadowing and add a test
  CHANGELOG.md
  example/calculate_pi/calculate_pi.cpp
  src/interface/mesh_data.hpp
Labels: bug

#575 Make file comparison more verbose, don't check File metadata
  CHANGELOG.md
  CMakeLists.txt
  scripts/python/packages/parthenon_tools/parthenon_tools/phdf_diff.py
  src/mesh/mesh.cpp
Labels: Fix
