Repository parthenon-hpc-lab/parthenon, pull requests merged in 2022-08, with the labels that each got.

#682 Prolongate in one
  CHANGELOG.md
  scripts/python/packages/parthenon_tools/parthenon_tools/phdf_diff.py
  src/CMakeLists.txt
  src/basic_types.hpp
  src/bvals/bvals_refine.cpp
  src/bvals/cc/bvals_cc_in_one.cpp
  src/bvals/cc/bvals_cc_in_one.hpp
  src/globals.cpp
  src/globals.hpp
  src/interface/mesh_data.hpp
  src/kokkos_abstraction.hpp
  src/mesh/mesh_refinement.cpp
  src/mesh/mesh_refinement_ops.hpp
  src/mesh/refinement_cc_in_one.cpp
  src/mesh/refinement_cc_in_one.hpp
  src/parthenon_manager.cpp
  src/utils/utils.hpp
  tst/regression/test_suites/output_hdf5/output_hdf5.py
Labels: enhancement

#711 Rename flux correction routines
  CHANGELOG.md
  docs/sparse_boundary_communication.md
  example/advection/advection_driver.cpp
  example/particle_tracers/particle_tracers.cpp
  example/sparse_advection/sparse_advection_driver.cpp
  example/stochastic_subgrid/stochastic_subgrid_driver.cpp
  src/bvals/cc/bvals_cc_in_one.hpp
  src/bvals/cc/sparse_flux_correction_cc_in_one.cpp
Labels: api

#712 Allow to add params from cmdline
  CHANGELOG.md
  docs/README.md
  src/parameter_input.cpp
  tst/regression/test_suites/output_hdf5/output_hdf5.py
  tst/regression/test_suites/output_hdf5/parthinput.advection
Labels: enhancement

#719 [small] fix type mismatch
  CHANGELOG.md
  src/bvals/bvals_swarm.cpp
Labels: bug
