Repository parthenon-hpc-lab/parthenon, pull requests merged in 2022-12, with the labels that each got.

#769 userspace prolongation
  CHANGELOG.md
  benchmarks/burgers/burgers_driver.cpp
  benchmarks/burgers/burgers_package.cpp
  benchmarks/burgers/burgers_package.hpp
  benchmarks/burgers/recon.hpp
  docs/boundary_communication.md
  docs/interface/RefinementOperations.md
  docs/parthenon_arrays.md
  example/advection/advection_driver.cpp
  example/particle_tracers/particle_tracers.cpp
  example/poisson/poisson_driver.cpp
  example/sparse_advection/sparse_advection_driver.cpp
  example/stochastic_subgrid/stochastic_subgrid_driver.cpp
  src/CMakeLists.txt
  src/bvals/bvals.hpp
  src/bvals/bvals_refine.cpp
  src/bvals/cc/bnd_info.cpp
  src/bvals/cc/bnd_info.hpp
  src/bvals/cc/boundary_communication.cpp
  src/bvals/cc/build_boundary_buffers.cpp
  src/bvals/cc/bvals_cc_in_one.hpp
  src/bvals/cc/bvals_utils.hpp
  src/bvals/cc/flux_correction.cpp
  src/bvals/cc/tag_map.cpp
  src/globals.cpp
  src/globals.hpp
  src/interface/mesh_data.hpp
  src/interface/metadata.hpp
  src/interface/packages.hpp
  src/interface/state_descriptor.cpp
  src/interface/state_descriptor.hpp
  src/interface/variable.hpp
  src/interface/variable_state.cpp
  src/interface/variable_state.hpp
  src/mesh/amr_loadbalance.cpp
  src/mesh/mesh.cpp
  src/mesh/mesh_refinement.cpp
  src/mesh/mesh_refinement.hpp
  src/mesh/mesh_refinement_loops.hpp
  src/mesh/mesh_refinement_ops.hpp
  src/mesh/meshblock.hpp
  src/mesh/refinement_cc_in_one.cpp
  src/mesh/refinement_in_one.cpp
  src/mesh/refinement_in_one.hpp
  src/parthenon_array_generic.hpp
  src/parthenon_manager.cpp
  src/refinement/amr_criteria.cpp
  src/utils/communication_buffer.hpp
  tst/unit/test_metadata.cpp
  tst/unit/test_pararrays.cpp
  tst/unit/test_state_descriptor.cpp
Labels: enhancement

#800 Fixes #659 (rare and intermitted race condition to set allocation status)
  CHANGELOG.md
  docs/development.md
  docs/nested_par_for.md
  src/bvals/cc/boundary_communication.cpp
  src/interface/update.cpp
Labels: bug

#797 Bug fix in boundary communication
  CHANGELOG.md
  src/bvals/cc/build_boundary_buffers.cpp
  src/bvals/cc/bvals_utils.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  tst/style/cpplint.py
Labels: bug

#775 refinement reorg
  CHANGELOG.md
  benchmarks/burgers/burgers_driver.cpp
  example/advection/advection_driver.cpp
  example/particle_tracers/particle_tracers.cpp
  example/poisson/poisson_driver.cpp
  example/sparse_advection/sparse_advection_driver.cpp
  example/stochastic_subgrid/stochastic_subgrid_driver.cpp
  src/CMakeLists.txt
  src/amr_criteria/amr_criteria.cpp
  src/amr_criteria/amr_criteria.hpp
  src/amr_criteria/refinement_package.cpp
  src/amr_criteria/refinement_package.hpp
  src/basic_types.hpp
  src/bvals/bvals.hpp
  src/bvals/bvals_refine.cpp
  src/bvals/cc/bnd_info.cpp
  src/bvals/cc/boundary_communication.cpp
  src/bvals/cc/build_boundary_buffers.cpp
  src/bvals/cc/bvals_cc_in_one.hpp
  src/bvals/cc/bvals_utils.hpp
  src/bvals/cc/flux_correction.cpp
  src/bvals/cc/tag_map.cpp
  src/interface/metadata.hpp
  src/interface/state_descriptor.hpp
  src/interface/variable.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh_refinement.cpp
  src/mesh/mesh_refinement.hpp
  src/parthenon_manager.cpp
  src/prolong_restrict/pr_loops.hpp
  src/prolong_restrict/pr_ops.hpp
  src/prolong_restrict/prolong_restrict.cpp
  src/prolong_restrict/prolong_restrict.hpp
  src/utils/communication_buffer.hpp
  src/utils/gl_quadrature.cpp
  src/utils/gl_quadrature.hpp
  src/utils/interp_table.cpp
  src/utils/interp_table.hpp
  src/utils/loop_utils.hpp
  tst/unit/test_metadata.cpp
  tst/unit/test_state_descriptor.cpp
Labels: enhancement, breaks-downstream
