Repository parthenon-hpc-lab/parthenon, pull requests merged in 2023-06, with the labels that each got.

#877 Add flat sparse packs
  CHANGELOG.md
  doc/sphinx/src/interface/sparse.rst
  src/interface/sparse_pack.hpp
  src/interface/sparse_pack_base.cpp
  src/interface/sparse_pack_base.hpp
  tst/unit/test_sparse_pack.cpp
Labels: enhancement, Kokkos, performance

#872 Boundary communication for non-cell centered fields
  CHANGELOG.md
  CMakeLists.txt
  benchmarks/burgers/burgers_driver.cpp
  doc/sphinx/src/boundary_communication.rst
  doc/sphinx/src/interface/refinement_operations.rst
  example/advection/advection_driver.cpp
  example/particle_tracers/particle_tracers.cpp
  example/sparse_advection/sparse_advection_driver.cpp
  example/stochastic_subgrid/stochastic_subgrid_driver.cpp
  scripts/python/packages/parthenon_tools/parthenon_tools/phdf_diff.py
  src/CMakeLists.txt
  src/basic_types.hpp
  src/bvals/boundary_conditions.cpp
  src/bvals/boundary_conditions.hpp
  src/bvals/comms/bnd_info.cpp
  src/bvals/comms/bnd_info.hpp
  src/bvals/comms/boundary_communication.cpp
  src/bvals/comms/build_boundary_buffers.cpp
  src/bvals/comms/bvals_in_one.hpp
  src/bvals/comms/bvals_utils.hpp
  src/bvals/comms/flux_correction.cpp
  src/bvals/comms/tag_map.cpp
  src/coordinates/uniform_cartesian.hpp
  src/interface/mesh_data.hpp
  src/interface/metadata.cpp
  src/interface/metadata.hpp
  src/interface/sparse_pack.hpp
  src/interface/sparse_pack_base.cpp
  src/interface/update.cpp
  src/kokkos_abstraction.hpp
  src/mesh/domain.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh_refinement.cpp
  src/mesh/meshblock.hpp
  src/prolong_restrict/pr_loops.hpp
  src/prolong_restrict/pr_ops.hpp
  src/prolong_restrict/prolong_restrict.cpp
  src/prolong_restrict/prolong_restrict.hpp
  src/utils/indexer.hpp
  src/utils/loop_utils.hpp
  tst/unit/test_metadata.cpp
  tst/unit/test_state_descriptor.cpp
Labels: enhancement, breaks-downstream

#889 add precommfillderived
  CHANGELOG.md
  src/interface/state_descriptor.hpp
  src/interface/update.hpp
  src/mesh/mesh.cpp
Labels: enhancement

#892 Meshblock Cost Function and Diagnostics
  CHANGELOG.md
  doc/sphinx/src/interface/sparse.rst
  doc/sphinx/src/load_balancing.rst
  example/sparse_advection/parthenon_app_inputs.cpp
  src/interface/meshblock_data.hpp
  src/interface/swarm.cpp
  src/interface/swarm.hpp
  src/interface/variable.cpp
  src/interface/variable.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  src/mesh/meshblock.cpp
  src/mesh/meshblock.hpp
  src/utils/object_pool.hpp
Labels: enhancement

#884 Add constant derivative boundary condition and expose `GenericBC`
  CHANGELOG.md
  src/CMakeLists.txt
  src/bvals/boundary_conditions.cpp
  src/bvals/boundary_conditions.hpp
  src/bvals/boundary_conditions_generic.hpp
  src/interface/sparse_pack_base.cpp
  src/interface/sparse_pack_base.hpp
Labels: enhancement

#887 param restarts
  CHANGELOG.md
  CMakeLists.txt
  doc/sphinx/src/inputs.rst
  doc/sphinx/src/interface/sparse.rst
  doc/sphinx/src/interface/state.rst
  doc/sphinx/src/load_balancing.rst
  doc/sphinx/src/tests.rst
  src/CMakeLists.txt
  src/interface/packages.hpp
  src/interface/params.cpp
  src/interface/params.hpp
  src/interface/state_descriptor.hpp
  src/interface/variable.cpp
  src/outputs/parthenon_hdf5.cpp
  src/outputs/parthenon_hdf5.hpp
  src/outputs/restart.cpp
  src/outputs/restart.hpp
  src/parthenon_array_generic.hpp
  src/parthenon_manager.cpp
  src/utils/concepts_lite.hpp
  tst/unit/test_unit_params.cpp
Labels: enhancement

#894 map instead of unordered_map for sparse pool
  CHANGELOG.md
  src/interface/sparse_pool.hpp
  tst/unit/test_state_descriptor.cpp
Labels: bug, breaks-downstream

#890 Fix Bugs in Sparse Communication
  CHANGELOG.md
  CMakeLists.txt
  src/bvals/boundary_conditions.cpp
  src/bvals/comms/bnd_info.cpp
  src/bvals/comms/bnd_info.hpp
  src/bvals/comms/boundary_communication.cpp
  src/bvals/comms/bvals_in_one.hpp
  src/bvals/comms/bvals_utils.hpp
  src/mesh/amr_loadbalance.cpp
  src/mesh/mesh.cpp
  src/utils/communication_buffer.hpp
Labels: bug
