Repository parthenon-hpc-lab/parthenon, pull requests merged in 2023-11, with the labels that each got.

#962 Add support for in-situ histograms/profiles
  CHANGELOG.md
  doc/sphinx/src/boundary_communication.rst
  doc/sphinx/src/figs/Curtis_et_al-ApJL-2023-1dhist.png
  doc/sphinx/src/figs/TaskDiagram.png
  doc/sphinx/src/figs/yt_doc-2dhist.png
  doc/sphinx/src/interface/state.rst
  doc/sphinx/src/mesh/mesh.rst
  doc/sphinx/src/outputs.rst
  doc/sphinx/src/tasks.rst
  src/CMakeLists.txt
  src/outputs/histogram.cpp
  src/outputs/outputs.cpp
  src/outputs/outputs.hpp
  src/utils/signal_handler.cpp
  src/utils/sort.hpp
  tst/regression/test_suites/output_hdf5/output_hdf5.py
  tst/regression/test_suites/output_hdf5/parthinput.advection
  tst/unit/CMakeLists.txt
  tst/unit/test_upper_bound.cpp
Labels: enhancement

#974 make get parent pointer consistent
  CHANGELOG.md
  example/poisson/poisson_package.cpp
  src/amr_criteria/refinement_package.cpp
  src/bvals/boundary_conditions.cpp
  src/bvals/boundary_conditions_generic.hpp
  src/bvals/comms/bnd_info.cpp
  src/bvals/comms/bnd_info.hpp
  src/bvals/comms/boundary_communication.cpp
  src/bvals/comms/build_boundary_buffers.cpp
  src/bvals/comms/bvals_utils.hpp
  src/bvals/comms/tag_map.cpp
  src/bvals/comms/tag_map.hpp
  src/interface/meshblock_data.hpp
  src/interface/update.cpp
  src/mesh/amr_loadbalance.cpp
Labels: refactor, breaks-downstream

#978 [trivial] remove check that got reintroduced
  CHANGELOG.md
  src/bvals/comms/bnd_info.cpp
Labels: bug
