Repository parthenon-hpc-lab/parthenon, pull requests merged in 2023-02, with the labels that each got.

#818 Bug Fix: Boundary prolongation only occurring on base stage
  CHANGELOG.md
  CMakeLists.txt
  src/CMakeLists.txt
  src/bvals/boundary_conditions.cpp
  src/bvals/bvals.hpp
  src/bvals/bvals_refine.cpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/mesh/amr_loadbalance.cpp
  src/mesh/mesh_refinement.cpp
  src/mesh/mesh_refinement.hpp
  tst/regression/test_suites/output_hdf5/output_hdf5.py
  tst/regression/test_suites/sparse_advection/sparse_advection.py
Labels: bug

#824 Fix exception throwing on device in `UniformCartesian`
  CHANGELOG.md
  src/coordinates/uniform_cartesian.hpp
Labels: bug

#814 make sphinx doc deploy on develop proper
  .github/workflows/docs.yml
Labels: bug, documentation

#829 More IO cleanup
  CHANGELOG.md
  src/CMakeLists.txt
  src/outputs/formatted_table.cpp
  src/outputs/outputs.cpp
  src/outputs/outputs.hpp
Labels: enhancement

#831 Metadata Upgrade
  CHANGELOG.md
  doc/sphinx/src/interface/metadata.rst
  doc/sphinx/src/sphinx-doc.rst
  src/CMakeLists.txt
  src/interface/mesh_data.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/interface/metadata.cpp
  src/interface/metadata.hpp
  src/interface/swarm.hpp
  src/interface/swarm_container.cpp
  src/interface/swarm_container.hpp
  src/interface/update.hpp
  src/interface/variable.cpp
  src/interface/variable.hpp
  src/interface/variable_pack.hpp
  src/mesh/amr_loadbalance.cpp
  src/mesh/mesh_refinement.cpp
  src/mesh/mesh_refinement.hpp
  src/mesh/meshblock.cpp
  src/utils/unique_id.cpp
  src/utils/unique_id.hpp
  tst/unit/test_meshblock_data_iterator.cpp
  tst/unit/test_metadata.cpp
Labels: enhancement
