Repository parthenon-hpc-lab/parthenon, pull requests merged in 2024-05, with the labels that each got.

#1070 correctly exclude flux vars from searches by default
  CHANGELOG.md
  doc/sphinx/src/interface/metadata.rst
  src/basic_types.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/interface/metadata.hpp
  src/utils/error_checking.hpp
  tst/unit/test_meshblock_data_iterator.cpp
Labels: bug

#1037 Add SwarmPacks
  CHANGELOG.md
  doc/sphinx/src/particles.rst
  example/particle_leapfrog/particle_leapfrog.cpp
  example/particle_tracers/particle_tracers.cpp
  example/particles/particles.cpp
  scripts/python/packages/parthenon_tools/parthenon_tools/phdf.py
  src/CMakeLists.txt
  src/interface/make_swarm_pack_descriptor.hpp
  src/interface/mesh_data.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/interface/pack_utils.hpp
  src/interface/sparse_pack.hpp
  src/interface/sparse_pack_base.cpp
  src/interface/swarm.cpp
  src/interface/swarm.hpp
  src/interface/swarm_comms.cpp
  src/interface/swarm_default_names.hpp
  src/interface/swarm_pack.hpp
  src/interface/swarm_pack_base.hpp
  src/kokkos_abstraction.hpp
  src/mesh/mesh.cpp
  src/mesh/meshblock.cpp
  src/mesh/meshblock.hpp
  src/outputs/output_utils.cpp
  src/outputs/outputs.cpp
  src/outputs/parthenon_xdmf.cpp
  src/parthenon/package.hpp
  src/parthenon/prelude.hpp
  src/parthenon_manager.cpp
  src/parthenon_manager.hpp
  tst/performance/test_meshblock_data_iterator.cpp
  tst/unit/CMakeLists.txt
  tst/unit/test_meshblock_data_iterator.cpp
  tst/unit/test_swarm.cpp
Labels: enhancement, api, breaks-downstream

#1071 Fix bug in static refinement
  CHANGELOG.md
  src/mesh/forest/forest.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  tst/regression/CMakeLists.txt
  tst/regression/test_suites/sparse_advection/sparse_advection.py
Labels: bug

#1078 A few Kokkos quality of life improvements
  CHANGELOG.md
  src/basic_types.hpp
  src/kokkos_abstraction.hpp
  src/mesh/domain.hpp
  src/prolong_restrict/pr_loops.hpp
  tst/unit/kokkos_abstraction.cpp
Labels: bug, enhancement, api

#1081 [Trivial] add GetSize and GetIndex to sparse pack
  CHANGELOG.md
  src/interface/sparse_pack.hpp
  tst/unit/test_sparse_pack.cpp
Labels: enhancement

#1084 Properly free swarm boundary MPI requests
  CHANGELOG.md
  src/interface/swarm_comms.cpp
Labels: bug

#1083 Correctly fill VariableFluxPack for edge fluxes in 2D
  CHANGELOG.md
  src/interface/variable_pack.hpp
Labels: bug

#1089 Fix restaring from files not containing the derefinement counter (from #1073)
  CHANGELOG.md
  scripts/python/packages/parthenon_tools/parthenon_tools/phdf_diff.py
  src/mesh/mesh.cpp
  src/outputs/output_utils.cpp
  src/outputs/output_utils.hpp
  src/outputs/parthenon_hdf5.cpp
  src/outputs/restart.hpp
  src/outputs/restart_hdf5.cpp
  tst/regression/test_suites/restart/parthinput.restart
Labels: bug
