Repository parthenon-hpc-lab/parthenon, pull requests merged in 2024-06, with the labels that each got.

#1095 add missing include guard for hdf5 restart
  CHANGELOG.md
  src/outputs/restart_hdf5.cpp
Labels: bug, io, Fix

#1098 Bugfix: Resymmetrize logical coordinates
  CHANGELOG.md
  src/defs.hpp
  src/mesh/forest/forest.cpp
  src/mesh/forest/logical_location.cpp
  src/mesh/forest/logical_location.hpp
  src/mesh/forest/tree.cpp
  src/mesh/mesh.cpp
Labels: bug

#1104 Fix reading restarts due to hidden ghost var
  CHANGELOG.md
  src/outputs/restart.hpp
  src/outputs/restart_hdf5.cpp
  src/outputs/restart_hdf5.hpp
  src/parthenon_manager.cpp
Labels: bug

#1112 Small Bugfix: Remove `shared_ptr` cycle in `Tree`
  CHANGELOG.md
  src/mesh/forest/tree.cpp
  src/mesh/forest/tree.hpp
Labels: bug

#1113 Small Bugfix: Prevent division by zero
  CHANGELOG.md
  example/poisson/poisson_package.cpp
  src/solvers/mg_solver.hpp
Labels: bug

#1092 Updates to `DataCollection`
  CHANGELOG.md
  example/fine_advection/advection_driver.cpp
  src/interface/data_collection.cpp
  src/interface/data_collection.hpp
  src/interface/mesh_data.cpp
  src/interface/mesh_data.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/mesh/mesh-amr_loadbalance.cpp
  src/mesh/mesh.cpp
  src/mesh/meshblock.cpp
  src/outputs/history.cpp
  src/utils/concepts_lite.hpp
  tst/unit/test_index_split.cpp
  tst/unit/test_mesh_data.cpp
  tst/unit/test_sparse_pack.cpp
Labels: bug

#1111 Small Bugfix: Remove possibility of bitshifting negative integers
  CHANGELOG.md
  src/mesh/forest/logical_location.cpp
Labels: bug

#1124 result_of -> invoke_result
  src/tasks/thread_pool.hpp
Labels: C++17

#1114 Enable sanitizers for extended CI host build
  .github/workflows/ci-extended.yml
  CHANGELOG.md
Labels: ci, testing

#1127 Add WithFluxes to IsRefined check
  CHANGELOG.md
  src/bvals/comms/bnd_info.cpp
  src/interface/metadata.cpp
  src/interface/metadata.hpp
  src/interface/state_descriptor.hpp
  src/interface/variable.hpp
  tst/unit/test_metadata.cpp
Labels: bug

#1128 Add cycle and nbtotal to hst
  CHANGELOG.md
  benchmarks/burgers/burgers_diff.py
  benchmarks/burgers/burgers_package.cpp
  benchmarks/burgers/burgers_package.hpp
  src/outputs/history.cpp
  tst/regression/test_suites/output_hdf5/output_hdf5.py
  tst/unit/test_metadata.cpp
Labels: breaks-downstream
