Repository parthenon-hpc-lab/parthenon, pull requests merged in 2024-03, with the labels that each got.

#1023 fix param bool bug
  CHANGELOG.md
  src/outputs/parthenon_hdf5_attributes.cpp
  tst/unit/test_unit_params.cpp
Labels: bug

#973 MG performance upgrades
  CHANGELOG.md
  example/poisson_gmg/main.cpp
  example/poisson_gmg/poisson_driver.cpp
  example/poisson_gmg/poisson_driver.hpp
  example/poisson_gmg/poisson_package.cpp
  src/bvals/boundary_conditions_generic.hpp
  src/interface/mesh_data.cpp
  src/interface/sparse_pack.hpp
  src/solvers/bicgstab_solver.hpp
  src/solvers/mg_solver.hpp
  src/solvers/solver_utils.hpp
Labels: breaks-downstream

#1031 Bug fix in non-cell centered AMR
  CHANGELOG.md
  src/mesh/amr_loadbalance.cpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
Labels: bug

#1027 Refactor `RestartReader` as abstract class
  CHANGELOG.md
  src/CMakeLists.txt
  src/mesh/mesh.cpp
  src/outputs/restart.hpp
  src/outputs/restart_hdf5.cpp
  src/outputs/restart_hdf5.hpp
  src/parthenon_manager.cpp
Labels: refactor
