Repository parthenon-hpc-lab/parthenon, pull requests merged in 2024-04, with the labels that each got.

#1024 Add features to history output
  .github/workflows/ci-extended.yml
  CHANGELOG.md
  doc/sphinx/src/interface/state.rst
  doc/sphinx/src/outputs.rst
  example/advection/advection_package.cpp
  example/advection/advection_package.hpp
  example/advection/parthinput.advection
  src/outputs/history.cpp
  src/outputs/outputs.cpp
  src/outputs/outputs.hpp
  tst/regression/test_suites/output_hdf5/output_hdf5.py
Labels: breaks-downstream

#1004 Allow parameter modification from an input file for restarts
  CHANGELOG.md
  doc/sphinx/src/README.rst
  doc/sphinx/src/outputs.rst
  src/argument_parser.hpp
  src/parthenon_manager.cpp
  tst/regression/test_suites/restart/parthinput_override.restart
  tst/regression/test_suites/restart/restart.py
Labels: enhancement

#1039 custom coords
  CHANGELOG.md
  CMakeLists.txt
  doc/sphinx/src/interface/metadata.rst
  doc/sphinx/src/outputs.rst
  example/sparse_advection/sparse_advection_package.cpp
  src/interface/metadata.cpp
  src/interface/metadata.hpp
  src/outputs/output_utils.hpp
  src/outputs/parthenon_hdf5.cpp
  src/outputs/parthenon_xdmf.cpp
Labels: enhancement

#1053 Set the correct root level on restart
  CHANGELOG.md
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
Labels: bug

#1035 Fix Multigrid Solver in Forest
  .github/workflows/ci-extended.yml
  CHANGELOG.md
  doc/sphinx/src/mesh/mesh.rst
  src/basic_types.hpp
  src/driver/driver.cpp
  src/interface/data_collection.cpp
  src/interface/mesh_data.cpp
  src/interface/mesh_data.hpp
  src/mesh/forest/block_ownership.cpp
  src/mesh/forest/block_ownership.hpp
  src/mesh/forest/forest.cpp
  src/mesh/forest/forest.hpp
  src/mesh/forest/logical_location.cpp
  src/mesh/forest/logical_location.hpp
  src/mesh/forest/relative_orientation.hpp
  src/mesh/forest/tree.cpp
  src/mesh/forest/tree.hpp
  src/mesh/mesh-amr_loadbalance.cpp
  src/mesh/mesh-gmg.cpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  src/solvers/mg_solver.hpp
  src/utils/cell_center_offsets.hpp
  tst/unit/test_logical_location.cpp
Labels: bug

#1057 Fix history output after restarts
  CHANGELOG.md
  src/outputs/outputs.cpp
Labels: bug

#1042 [Small] Cleanup of `NeighborBlock`
  CHANGELOG.md
  src/bvals/bvals.cpp
  src/bvals/comms/bnd_info.cpp
  src/bvals/comms/build_boundary_buffers.cpp
  src/bvals/comms/bvals_utils.hpp
  src/bvals/comms/tag_map.cpp
  src/bvals/neighbor_block.cpp
  src/bvals/neighbor_block.hpp
  src/interface/swarm_comms.cpp
  src/utils/cell_center_offsets.hpp
  src/utils/loop_utils.hpp
Labels: breaks-downstream

#1058 Vector history not being output if no scalar history present
  CHANGELOG.md
  src/outputs/history.cpp
Labels: bug

#1060 Thread UIDs through `data_collection`
  CHANGELOG.md
  src/interface/data_collection.cpp
  src/interface/data_collection.hpp
  src/interface/mesh_data.cpp
  src/interface/mesh_data.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/mesh/mesh.hpp
  tst/unit/test_data_collection.cpp
Labels: enhancement

#1064 add fail on edge case in Mesh Data
  CHANGELOG.md
  src/interface/mesh_data.cpp
  src/interface/mesh_data.hpp
Labels: bug

#1066 Add default loop patterns back into the global par_loops
  CHANGELOG.md
  doc/sphinx/src/nested_par_for.rst
  example/kokkos_pi/kokkos_pi.cpp
  example/poisson/poisson_package.cpp
  example/poisson_gmg/poisson_equation.hpp
  src/interface/update.cpp
  src/interface/update.hpp
  src/kokkos_abstraction.hpp
  src/mesh/mesh-amr_loadbalance.cpp
  src/outputs/histogram.cpp
  src/prolong_restrict/pr_loops.hpp
  src/solvers/mg_solver.hpp
Labels: enhancement, Kokkos, C++17

#1067 Enables compilation with nvhpc-sdk.
  src/CMakeLists.txt
Labels: bug
