Repository parthenon-hpc-lab/parthenon, pull requests merged in 2025-07, with the labels that each got.

#1276 Specialize `Kokkos::reduction_identity` for `AmrTag`
  CHANGELOG.md
  src/amr_criteria/refinement_package.hpp
  src/basic_types.hpp
Labels: bug

#1266 Refactor output logic to not stash next output time/iteration in Params
  CHANGELOG.md
  CMakeLists.txt
  doc/sphinx/src/outputs.rst
  src/CMakeLists.txt
  src/interface/state_descriptor.hpp
  src/outputs/ascent.cpp
  src/outputs/histogram.cpp
  src/outputs/history.cpp
  src/outputs/output_parameters.hpp
  src/outputs/outputs.cpp
  src/outputs/outputs.hpp
  src/outputs/outputs_package.cpp
  src/outputs/outputs_package.hpp
  src/outputs/parthenon_hdf5.cpp
  src/parameter_input.hpp
  src/parthenon_manager.cpp
  tst/regression/utils/test_case.py
  tst/unit/test_parameter_input.cpp
  tst/unit/test_state_descriptor.cpp
  tst/unit/test_unit_params.cpp
Labels: refactor, io

#1281 params -> std::any
  CHANGELOG.md
  src/interface/params.cpp
  src/interface/params.hpp
  src/interface/state_descriptor.hpp
  tst/unit/test_unit_params.cpp
Labels: refactor

#1286 Add ParameterRef
  CHANGELOG.md
  doc/sphinx/src/generated/diffusion-parth-table.csv
  src/mesh/mesh.cpp
  src/parameter_input.cpp
  src/parameter_input.hpp
Labels: documentation, enhancement

#1283 docstrings and provenance
  .github/workflows/docs.yml
  CHANGELOG.md
  CMakeLists.txt
  benchmarks/burgers/CMakeLists.txt
  doc/sphinx/_static/custom.css
  doc/sphinx/conf.py
  doc/sphinx/src/0_input_parameters_ref.rst
  doc/sphinx/src/generated/burgers-table.csv
  doc/sphinx/src/generated/diffusion-parth-table.csv
  doc/sphinx/src/generated/diffusion-table.csv
  example/advection/advection_package.cpp
  example/diffusion/CMakeLists.txt
  src/amr_criteria/amr_criteria.cpp
  src/amr_criteria/refinement_package.cpp
  src/argument_parser.hpp
  src/driver/driver.cpp
  src/driver/driver.hpp
  src/globals.cpp
  src/globals.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  src/mesh/mesh_refinement.cpp
  src/mesh/meshblock.hpp
  src/outputs/outputs.cpp
  src/outputs/outputs_package.cpp
  src/parameter_input.cpp
  src/parameter_input.hpp
  src/parthenon_manager.cpp
  src/utils/sort.hpp
Labels: documentation, enhancement
