Repository parthenon-hpc-lab/parthenon, pull requests merged in 2025-02, with the labels that each got.

#1182 Add a `MeshData` variant for refinement tagging
  CHANGELOG.md
  benchmarks/burgers/burgers_driver.cpp
  doc/sphinx/src/interface/state.rst
  example/fine_advection/advection_package.cpp
  example/fine_advection/advection_package.hpp
  src/amr_criteria/amr_criteria.cpp
  src/amr_criteria/amr_criteria.hpp
  src/amr_criteria/refinement_package.cpp
  src/amr_criteria/refinement_package.hpp
  src/interface/state_descriptor.hpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  src/mesh/mesh_refinement.cpp
  src/mesh/mesh_refinement.hpp
  src/parthenon_array_generic.hpp
Labels: enhancement, performance, refactor

#1174 [Breaking] Linear Solver Updates
  CHANGELOG.md
  doc/sphinx/src/solvers.rst
  example/poisson_gmg/plot_convergence.py
  example/poisson_gmg/poisson_driver.cpp
  example/poisson_gmg/poisson_equation.hpp
  example/poisson_gmg/poisson_package.cpp
  src/CMakeLists.txt
  src/basic_types.hpp
  src/interface/sparse_pack.hpp
  src/interface/sparse_pack_base.cpp
  src/interface/sparse_pack_base.hpp
  src/mesh/meshblock.hpp
  src/solvers/bicgstab_solver.hpp
  src/solvers/cg_solver.hpp
  src/solvers/internal_prolongation.hpp
  src/solvers/mg_solver.hpp
  src/solvers/solver_base.hpp
  src/solvers/solver_utils.hpp
  src/utils/indexer.hpp
  src/utils/type_list.hpp
Labels: enhancement, breaks-downstream

#1137 [Breaking] Another stab at more general coordinate support
  CHANGELOG.md
  doc/sphinx/src/coordinates.rst
  example/poisson/poisson_package.cpp
  src/CMakeLists.txt
  src/coordinates/coordinates.hpp
  src/coordinates/uniform_cartesian.hpp
  src/coordinates/uniform_coordinates.hpp
  src/coordinates/uniform_cylindrical.hpp
  src/coordinates/uniform_spherical.hpp
  src/interface/swarm_device_context.hpp
  src/prolong_restrict/pr_ops.hpp
  src/utils/index_split.hpp
  tst/unit/CMakeLists.txt
  tst/unit/test_coordinates.cpp
Labels: breaks-downstream
