Repository parthenon-hpc-lab/parthenon, pull requests merged in 2025-09, with the labels that each got.

#1192 Coalesced Buffer Communication
  CHANGELOG.md
  doc/sphinx/src/boundary_communication.rst
  doc/sphinx/src/generated/diffusion-parth-table.csv
  example/fine_advection/advection_driver.cpp
  src/CMakeLists.txt
  src/basic_types.hpp
  src/bvals/comms/bnd_id.cpp
  src/bvals/comms/bnd_id.hpp
  src/bvals/comms/bnd_info.cpp
  src/bvals/comms/bnd_info.hpp
  src/bvals/comms/boundary_communication.cpp
  src/bvals/comms/build_boundary_buffers.cpp
  src/bvals/comms/bvals_utils.hpp
  src/bvals/comms/coalesced_buffers.cpp
  src/bvals/comms/coalesced_buffers.hpp
  src/interface/data_collection.cpp
  src/interface/data_collection.hpp
  src/interface/mesh_data.hpp
  src/interface/meshblock_data.cpp
  src/interface/meshblock_data.hpp
  src/interface/swarm.cpp
  src/interface/variable.hpp
  src/mesh/mesh-amr_loadbalance.cpp
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
  src/utils/communication_buffer.hpp
  src/utils/mpi_types.hpp
  src/utils/unique_id.hpp
  tst/regression/CMakeLists.txt
  tst/regression/test_suites/restart_fine/restart_fine.py
Labels: possibly breaking

#1324 [Trivial] fix erroneous error message in static refinement
  CHANGELOG.md
  src/mesh/mesh.cpp
  src/mesh/mesh.hpp
Labels: bug

#1323 Pull out sparse dealloc into a templated function, move it out of update
  CHANGELOG.md
  doc/sphinx/src/interface/sparse.rst
  src/CMakeLists.txt
  src/interface/mesh_data.hpp
  src/interface/meshblock_data.hpp
  src/interface/update.cpp
  src/interface/update.hpp
  src/sparse/sparse_management.cpp
  src/sparse/sparse_management.hpp
Labels: enhancement, api

#1328 [trivial] more useful error message for timeouts
  CHANGELOG.md
  src/tasks/thread_pool.hpp
Labels: documentation
